name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    uses: ./.github/workflows/workflow-build-windows.yaml
  build-macos:
    uses: ./.github/workflows/workflow-build-macos.yaml
  build-ubuntu:
    uses: ./.github/workflows/workflow-build-ubuntu.yaml
  release:
    name: Release packages automatically when pushed a v* version tag
    needs: [build-windows, build-macos, build-ubuntu]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create info file
        run: |
          echo "ref: ${GITHUB_REF}" > info.txt
          echo "commit: ${GITHUB_SHA}" >> info.txt
          echo "build: $(date +"%Y-%m-%dT%H:%M:%SZ")" >> info.txt
      - name: Publish release builds
        uses: ncipollo/release-action@v1
        with:
          artifacts: info.txt, ubuntu/openmsx-debugger-ubuntu-gh.tbz, macos/openmsx-debugger-macos-gh.tbz, mingw32/openmsx-debugger-mingw32-gh.zip
          body: "Build number ${{ github.run_number }}\n${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          prerelease: true
          allowUpdates: true
          generateReleaseNotes: true
          updateOnlyUnreleased: true
